apiVersion: v1
kind: Pod
metadata:
  name: yc-s3-test-storage-pod
  namespace: default
spec:
  containers:
    - name: yc-s3-test-storage-pod
      image: busybox:1.31.1
      command: [ "sh", "-c", "dd if=/dev/zero of=/data/storage-test.img bs=1M count=256 && sleep 3600" ]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: csi-s3-pvc
        readOnly: false