apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otus-project
  namespace: argocd
spec:
  description: Otus homework project
  sourceRepos:
    - 'https://github.com/Kuber-2024-04OTUS/yourh3ro_repo.git'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
      name: in-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true