apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
  namespace: homework
  labels:
    app: webserver-svc
spec:
  type: ClusterIP
  selector: 
    app: webserver
  ports:
    - name: websrv-svc-port
      protocol: TCP
      port: 8000
      targetPort: webserver-port
