apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
stringData:
  prometheus-additional-job.yaml: |
    - job_name: "tekton-pipelines"
      scrape_interval: 30s
      static_configs:
      - targets: ["tekton-pipelines-controller.tekton-pipelines.svc.cluster.local:9090"]