---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: otus
  namespace: vault
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    vault:
      server: "http://vault.vault:8200"
      path: "otus"
      version: "v2"
      namespace: "vault"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "otus"
          serviceAccountRef:
            name: "vault-auth"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otus
  namespace: vault
spec:
  refreshInterval: 1h           
  secretStoreRef:
    kind: SecretStore
    name: otus   
  target:
    name: otus-cred
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cred