all:
  hosts:
    node1:
      ansible_host: 158.160.8.190
      ip: 10.129.0.6
      access_ip: 10.129.0.6
      ansible_user: yc-user
    node2:
      ansible_host: 158.160.6.7
      ip: 10.129.0.13
      access_ip: 10.129.0.13
      ansible_user: yc-user
    node3:
      ansible_host: 158.160.1.186
      ip: 10.129.0.17
      access_ip: 10.129.0.17
      ansible_user: yc-user
    node4:
      ansible_host: 158.160.29.116
      ip: 10.129.0.25
      access_ip: 10.129.0.25
      ansible_user: yc-user
    node5:
      ansible_host: 158.160.6.215
      ip: 10.129.0.29
      access_ip: 10.129.0.29
      ansible_user: yc-user
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
