apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: default
roleRef:
  kind: ClusterRole
  name: pipeline-cluster-role
  apiGroup: rbac.authorization.k8s.io
